name: Ruby CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [3.0, 2.7, 2.6, 2.5, 2.4, 2.3, 2.2, 2.1, 2.0]
    container: ruby:${{ matrix.ruby }}
    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ matrix.ruby }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-${{ matrix.ruby }}-
    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run tests
      run: bundle exec rake
